name: CI

on: [push, pull_request, pull_request_review]

jobs:
  test:
    name: Test on .NET Core ${{ matrix.dotnetcore_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnetcore_version: ['3.1.100']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use .NET Core ${{ matrix.dotnetcore_version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnetcore_version }}

    - name: .NET Core, build and test
      run: dotnet build
